## **Questions based on Titanic Dataset:**

To read the dataset as csv, use the below code:

```python
import pandas as pd

url = "https://docs.google.com/spreadsheets/d/e/2PACX-1vQjh5HzZ1N0SU7ME9ZQRzeVTaXaGsV97rU8R7eAcg53k27GTstJp9cRUOfr55go1GRRvTz1NwvyOnuh/pub?gid=1562145139&single=true&output=csv"
titanic_df = pd.read_csv(url)
```

In [2]:
import pandas as pd

url = "https://docs.google.com/spreadsheets/d/e/2PACX-1vQjh5HzZ1N0SU7ME9ZQRzeVTaXaGsV97rU8R7eAcg53k27GTstJp9cRUOfr55go1GRRvTz1NwvyOnuh/pub?gid=1562145139&single=true&output=csv"
titanic = pd.read_csv(url)

In [3]:
titanic.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [4]:
titanic["Embarked"].isna().sum()

2

### `Q-1:` Using `groupby` make groups using the `"Pclass"` column and find out the average age and total number of missing values in the `"Age"` column for every group.

In [5]:
pcls=titanic.groupby("Pclass")
for group in list(pcls.groups.keys()):
  print(f"class {group} : avg is {pcls.get_group(group)['Age'].mean()}")

class 1 : avg is 38.233440860215055
class 2 : avg is 29.87763005780347
class 3 : avg is 25.14061971830986

In [6]:
for group in list(pcls.groups.keys()):
  print(f"total number of missing value in each group {group} is {pcls.get_group(group)['Age'].isna().sum()}")

total number of missing value in each group 1 is 30
total number of missing value in each group 2 is 11
total number of missing value in each group 3 is 136

### `Q-2:` Using `groupby` make groups using the `"Pclass"` column and fill every group's `"Embarked"` column's missing values with the mode value of that group. After that, print every group's `"Embarked"` column's value counts in ascending order.

In [7]:
for group in list(pcls.groups.keys()):
  print("group is ",group,pcls.get_group(group)['Embarked'].isna().value_counts(ascending=True))

group is  1 Embarked
True       2
False    214
Name: count, dtype: int64
group is  2 Embarked
False    184
Name: count, dtype: int64
group is  3 Embarked
False    491
Name: count, dtype: int64

In [8]:
for group in list(pcls.groups.keys()):
  pcls.get_group(group)['Embarked'].fillna(pcls.get_group(group)['Embarked'].mode(),inplace=True)

<ipython-input-8-c79e0be921f3>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  pcls.get_group(group)['Embarked'].fillna(pcls.get_group(group)['Embarked'].mode(),inplace=True)

In [9]:
for group in list(pcls.groups.keys()):
  print("group is ",group,pcls.get_group(group)['Embarked'].isnull().value_counts(ascending=True))

group is  1 Embarked
True       2
False    214
Name: count, dtype: int64
group is  2 Embarked
False    184
Name: count, dtype: int64
group is  3 Embarked
False    491
Name: count, dtype: int64

### `Q-3:` Make groups based on `"Embarked"` column. And for each of this embarked group, make another group based on `"Pclass"` and find out the average fare (round off up to 2 decimal places) for each "Pclass" for each group of "Embarked".

**Sample Output:**

```bash
{'C': {1: 105, 2: 25, 3: 11},
 'Q': {1: 90, 2: 12, 3: 11},
 'S': {1: 70, 2: 20, 3: 15}}
```

In [10]:
ebrk=titanic.groupby("Embarked")

## **Questions Based on Fifa Worldcup - 2022 Dataset:**

You can read the dataset by using the below sample code

```python
import pandas as pd

fifa_df = pd.read_csv("https://docs.google.com/spreadsheets/d/e/2PACX-1vT3D_x_4DS6d51LKJ7ze1sxT5WpV5uiSVOFYHLwBiGru6vFyVv5h5-83AwFjxWYiWfCDjDAaarHAV-k/pub?gid=0&single=true&output=csv")
```

### `Q-4:` Perform `groupby` based on the `"Team"` column and then perform Z Normalization on top of the below columns of each group:
1. Passes
2. Passes Completed
3. Attempted Line Breaks
4. Completed Line Breaks

You have to make a python function named `z_normalization` which takes two arguments:

1. *group:* Every group that you have created
2. *cols_to_perform:* This parameter takes a list of columns on which you have to perform the Z-Normalization.

For this problem, you have to use th `apply()` method.

$\Large Z \ - \ Normalization = \frac{X_i - \mu}{std} $

After that find out the below values for each group:
- minimum "Passess"
- maximum "Passess"
- minimum "Yellow Cards"
- maximum "Yellow cards"
- average "Yellow Cards"
- maximum "Attempted Line Breaks"
- minimum "Attempted Line Breaks"
- standardard deviation of "Attempted Line Breaks"
- average Possession

## **Questions on IPL wala dataset**

ball by ball dataset - https://drive.google.com/file/d/1-kvv_9KCSAFWcrhS9WgTxSrURkRh6GNt/view?usp=share_link

### `Q-5:` Find batsman in below category-
* Highest score while chasing
* Best Strike rate while chasing and have faced 100+ balls


> Chasing mean team batting in second inning

In [11]:
ipl=pd.read_csv("ipl_deliveries.csv")

In [ ]:
ipl

,ID,Team,innings,overs,ballnumber,batter,bowler,non-striker,extra_type,batsman_run,extras_run,total_run,non_boundary,isWicketDelivery,player_out,kind,fielders_involved,BattingTeam,BowlingTeam
0,1312200,Rajasthan RoyalsGujarat Titans,1,0,1,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,0,0,0,0,NaN,NaN,NaN,Rajasthan Royals,Gujarat Titans
1,1312200,Rajasthan RoyalsGujarat Titans,1,0,2,YBK Jaiswal,Mohammed Shami,JC Buttler,legbyes,0,1,1,0,0,NaN,NaN,NaN,Rajasthan Royals,Gujarat Titans
2,1312200,Rajasthan RoyalsGujarat Titans,1,0,3,JC Buttler,Mohammed Shami,YBK Jaiswal,NaN,1,0,1,0,0,NaN,NaN,NaN,Rajasthan Royals,Gujarat Titans
3,1312200,Rajasthan RoyalsGujarat Titans,1,0,4,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,0,0,0,0,NaN,NaN,NaN,Rajasthan Royals,Gujarat Titans
4,1312200,Rajasthan RoyalsGujarat Titans,1,0,5,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,0,0,0,0,NaN,NaN,NaN,Rajasthan Royals,Gujarat Titans
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
225949,335982,Royal Challengers BangaloreKolkata Knight Riders,2,14,5,P Kumar,I Sharma,SB Joshi,legbyes,0,1,1,0,0,NaN,NaN,NaN,Royal Challengers Bangalore,Kolkata Knight Riders
225950,335982,Royal Challengers BangaloreKolkata Knight Riders,2,14,6,SB Joshi,I Sharma,P Kumar,NaN,1,0,1,0,0,NaN,NaN,NaN,Royal Challengers Bangalore,Kolkata Knight Riders
225951,335982,Royal Challengers BangaloreKolkata Knight Riders,2,14,7,P Kumar,I Sharma,SB Joshi,NaN,0,0,0,0,0,NaN,NaN,NaN,Royal Challengers Bangalore,Kolkata Knight Riders
225952,335982,Royal Challengers BangaloreKolkata Knight Riders,2,15,1,SB Joshi,LR Shukla,P Kumar,wides,0,1,1,0,0,NaN,NaN,NaN,Royal Challengers Bangalore,Kolkata Knight Riders
225953,335982,Royal Challengers BangaloreKolkata Knight Riders,2,15,2,SB Joshi,LR Shukla,P Kumar,NaN,0,0,0,0,1,SB Joshi,caught,BB McCullum,Royal Challengers Bangalore,Kolkata Knight Riders

In [12]:
#Highest score while chasing
ipl[ipl["innings"]==2].groupby(["ID","batter"])["batsman_run"].sum().sort_values(ascending=False).head()

ID       batter
1254061  SV Samson     119.0
1136620  SR Watson     117.0
1216541  BA Stokes     107.0
1312199  JC Buttler    106.0
1254073  D Padikkal    101.0
Name: batsman_run, dtype: float64

In [13]:
# Best Strike rate while chasing and have faced 100+ balls
temp2=ipl[ipl["extra_type"]!="Wides"]
temp3=temp2.groupby("batter").agg({"ballnumber":"count","batsman_run":"sum"})
temp3=temp3[temp3["ballnumber"]>=100]
temp3["SR"]=(temp3["batsman_run"]/temp3["ballnumber"]*100)
temp3.sort_values(by="SR",ascending=False)

                ballnumber  batsman_run          SR
batter
AD Russell             862       1465.0  169.953596
K Gowtham              115        186.0  161.739130
SP Narine              481        764.0  158.835759
JM Sharma              149        234.0  157.046980
AB de Villiers        1085       1695.0  156.221198
...                    ...          ...         ...
SE Rutherford          107        106.0   99.065421
KM Jadhav              328        315.0   96.036585
M Vijay                116        108.0   93.103448
Mohammed Siraj         111         96.0   86.486486
Kuldeep Yadav          108         85.0   78.703704

[125 rows x 3 columns]

### `Q-6` Most Successful bowler against any batsman. Find that pair of bowler and batsman.
> Most Successful in terms of dissmissal. A bowler who have dissmissed any batsman most no of times. If any two pairs have same no of dissmisal, consider runs conceded by bowler to that batsman. Those who have concede lesser runs is more successful.

In [14]:
temp=ipl[ipl["isWicketDelivery"]==1].groupby(["bowler","batter"])

In [15]:
temp.agg({"isWicketDelivery":"sum","total_run":"sum"}).sort_values(by=["isWicketDelivery","total_run"], ascending=[False,True])

                           isWicketDelivery  total_run
bowler       batter
DL Chahar    PP Shaw                    6.0        0.0
Shivam Mavi  SV Samson                  5.0        0.0
YS Chahal    MA Agarwal                 5.0        0.0
B Kumar      SR Watson                  4.0        0.0
DL Chahar    AM Rahane                  4.0        0.0
...                                     ...        ...
JO Holder    Harshit Rana               1.0        2.0
MG Johnson   DT Christian               1.0        2.0
S Lamichhane Shubman Gill               1.0        2.0
Yash Dayal   JC Buttler                 1.0        2.0
R Tewatia    RA Tripathi                1.0        6.0

[3137 rows x 2 columns]

### `Q-7`: Most successful batting pair in IPL. Batting pair who have scored most runs playing together.

In [23]:
import numpy as np
ipl.head()

,ID,Team,innings,overs,ballnumber,batter,bowler,non-striker,extra_type,batsman_run,extras_run,total_run,non_boundary,isWicketDelivery,player_out,kind,fielders_involved,BattingTeam,BowlingTeam
0,1312200,Rajasthan RoyalsGujarat Titans,1.0,0.0,1.0,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,Rajasthan Royals,Gujarat Titans
1,1312200,Rajasthan RoyalsGujarat Titans,1.0,0.0,2.0,YBK Jaiswal,Mohammed Shami,JC Buttler,legbyes,0.0,1.0,1.0,0.0,0.0,NaN,NaN,NaN,Rajasthan Royals,Gujarat Titans
2,1312200,Rajasthan RoyalsGujarat Titans,1.0,0.0,3.0,JC Buttler,Mohammed Shami,YBK Jaiswal,NaN,1.0,0.0,1.0,0.0,0.0,NaN,NaN,NaN,Rajasthan Royals,Gujarat Titans
3,1312200,Rajasthan RoyalsGujarat Titans,1.0,0.0,4.0,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,Rajasthan Royals,Gujarat Titans
4,1312200,Rajasthan RoyalsGujarat Titans,1.0,0.0,5.0,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,Rajasthan Royals,Gujarat Titans

In [52]:
def func(x):
  l=list(np.sort(x.values))
  ans=""
  ans= l[0]+l[1]
  return ans                  # seperator is not working here

  #return "-".join(list(np.sort(x.values)))
ipl["batting_pair"]=ipl[["batter","non-striker"]].apply(func,axis=1)

In [17]:
temp3=ipl.groupby(["batter","non-striker"])

In [45]:
ipl.groupby("batting_pair")["total_run"].sum().sort_values(ascending=False).head(5)

batting_pair
KL RahulMA Agarwal      1731.0
CH GayleKL Rahul        1605.0
PP ShawS Dhawan         1461.0
DA WarnerJM Bairstow    1401.0
RR PantSS Iyer          1311.0
Name: total_run, dtype: float64

In [51]:
#thsi is wrong way
temp3["total_run"].sum().sort_values(ascending=False).head(5)

batter      non-striker
MA Agarwal  KL Rahul       906.0
CH Gayle    KL Rahul       894.0
KL Rahul    MA Agarwal     825.0
PP Shaw     S Dhawan       816.0
RR Pant     SS Iyer        727.0
Name: total_run, dtype: float64

### `Q-8:` Make a dataframe for all batting pairs played together.
```
Batsman1 Batsman2 Runs Avg StrikeRate
```

> Just to ease this question you can count wide-balls for strike rate.

In [65]:
ipl.groupby("batting_pair").describe()

                         ID                                                 \
                      count          mean        std        min        25%
batting_pair
A BadoniDJ Hooda       90.0  1.304062e+06  22.542071  1304050.0  1304050.0
A BadoniE Lewis        18.0  1.304053e+06   0.000000  1304053.0  1304053.0
A BadoniJO Holder      15.0  1.304074e+06  20.790795  1304058.0  1304058.0
A BadoniKH Pandya      50.0  1.304068e+06  20.838162  1304050.0  1304050.0
A BadoniKL Rahul       45.0  1.304074e+06  13.425703  1304058.0  1304058.0
...                     ...           ...        ...        ...        ...
V ShankarVirat Singh   16.0  1.254066e+06   0.000000  1254066.0  1254066.0
V ShankarWP Saha        3.0  1.304075e+06   0.000000  1304075.0  1304075.0
V ShankarYK Pathan      9.0  1.175357e+06   0.000000  1175357.0  1175357.0
V ShankarYuvraj Singh  19.0  1.082648e+06   0.000000  1082648.0  1082648.0
WP SahaYK Pathan        9.0  1.136591e+06  10.013879  1136580.0  1136580.0

                                                       innings            ...  \
                             50%        75%        max   count      mean  ...
batting_pair                                                              ...
A BadoniDJ Hooda       1304050.0  1304050.0  1304103.0    90.0  1.233333  ...
A BadoniE Lewis        1304053.0  1304053.0  1304053.0    18.0  2.000000  ...
A BadoniJO Holder      1304058.0  1304099.0  1304099.0    15.0  1.000000  ...
A BadoniKH Pandya      1304058.0  1304093.5  1304099.0    50.0  1.200000  ...
A BadoniKL Rahul       1304083.0  1304083.0  1304109.0    45.0  1.022222  ...
...                          ...        ...        ...     ...       ...  ...
V ShankarVirat Singh   1254066.0  1254066.0  1254066.0    16.0  2.000000  ...
V ShankarWP Saha       1304075.0  1304075.0  1304075.0     3.0  2.000000  ...
V ShankarYK Pathan     1175357.0  1175357.0  1175357.0     9.0  1.000000  ...
V ShankarYuvraj Singh  1082648.0  1082648.0  1082648.0    19.0  1.000000  ...
WP SahaYK Pathan       1136599.0  1136599.0  1136599.0     9.0  1.444444  ...

                      isWicketDelivery       ball
                                   75%  max count mean std min 25% 50% 75% max
batting_pair
A BadoniDJ Hooda                   0.0  1.0   0.0  NaN NaN NaN NaN NaN NaN NaN
A BadoniE Lewis                    0.0  0.0   0.0  NaN NaN NaN NaN NaN NaN NaN
A BadoniJO Holder                  0.0  1.0   0.0  NaN NaN NaN NaN NaN NaN NaN
A BadoniKH Pandya                  0.0  1.0   0.0  NaN NaN NaN NaN NaN NaN NaN
A BadoniKL Rahul                   0.0  1.0   0.0  NaN NaN NaN NaN NaN NaN NaN
...                                ...  ...   ...  ...  ..  ..  ..  ..  ..  ..
V ShankarVirat Singh               0.0  1.0   0.0  NaN NaN NaN NaN NaN NaN NaN
V ShankarWP Saha                   0.5  1.0   0.0  NaN NaN NaN NaN NaN NaN NaN
V ShankarYK Pathan                 0.0  1.0   0.0  NaN NaN NaN NaN NaN NaN NaN
V ShankarYuvraj Singh              0.0  1.0   0.0  NaN NaN NaN NaN NaN NaN NaN
WP SahaYK Pathan                   0.0  1.0   0.0  NaN NaN NaN NaN NaN NaN NaN

[1514 rows x 80 columns]

,ID,Team,innings,overs,ballnumber,batter,bowler,non-striker,extra_type,batsman_run,...,total_run,non_boundary,isWicketDelivery,player_out,kind,fielders_involved,BattingTeam,BowlingTeam,batting_pair,ball
0,1312200,Rajasthan RoyalsGujarat Titans,1.0,0.0,1.0,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0.0,...,0.0,0.0,0.0,NaN,NaN,NaN,Rajasthan Royals,Gujarat Titans,JC ButtlerYBK Jaiswal,NaN
1,1312200,Rajasthan RoyalsGujarat Titans,1.0,0.0,2.0,YBK Jaiswal,Mohammed Shami,JC Buttler,legbyes,0.0,...,1.0,0.0,0.0,NaN,NaN,NaN,Rajasthan Royals,Gujarat Titans,JC ButtlerYBK Jaiswal,NaN
2,1312200,Rajasthan RoyalsGujarat Titans,1.0,0.0,3.0,JC Buttler,Mohammed Shami,YBK Jaiswal,NaN,1.0,...,1.0,0.0,0.0,NaN,NaN,NaN,Rajasthan Royals,Gujarat Titans,JC ButtlerYBK Jaiswal,NaN
3,1312200,Rajasthan RoyalsGujarat Titans,1.0,0.0,4.0,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0.0,...,0.0,0.0,0.0,NaN,NaN,NaN,Rajasthan Royals,Gujarat Titans,JC ButtlerYBK Jaiswal,NaN
4,1312200,Rajasthan RoyalsGujarat Titans,1.0,0.0,5.0,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0.0,...,0.0,0.0,0.0,NaN,NaN,NaN,Rajasthan Royals,Gujarat Titans,JC ButtlerYBK Jaiswal,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
76752,1082645,Rising Pune SupergiantKings XI Punjab,2.0,7.0,5.0,SPD Smith,AR Patel,AM Rahane,NaN,1.0,...,1.0,0.0,0.0,NaN,NaN,NaN,Rising Pune Supergiant,Kings XI Punjab,AM RahaneSPD Smith,NaN
76753,1082645,Rising Pune SupergiantKings XI Punjab,2.0,7.0,6.0,AM Rahane,AR Patel,SPD Smith,NaN,1.0,...,1.0,0.0,0.0,NaN,NaN,NaN,Rising Pune Supergiant,Kings XI Punjab,AM RahaneSPD Smith,NaN
76754,1082645,Rising Pune SupergiantKings XI Punjab,2.0,8.0,1.0,AM Rahane,R Tewatia,SPD Smith,NaN,0.0,...,0.0,0.0,0.0,NaN,NaN,NaN,Rising Pune Supergiant,Kings XI Punjab,AM RahaneSPD Smith,NaN
76755,1082645,Rising Pune SupergiantKings XI Punjab,2.0,8.0,2.0,AM Rahane,R Tewatia,SPD Smith,NaN,1.0,...,1.0,0.0,0.0,NaN,NaN,NaN,Rising Pune Supergiant,Kings XI Punjab,AM RahaneSPD Smith,NaN
76756,1082645,Rising Pune Supergia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN